#!/usr/bin/env bash
# BioSCADA AI — end-to-end demo.
# Drives every phase through the API and prints the result.
#
# Requires the API to be running:  ./scripts/run-local.sh
# Uses Python (already a project dependency) rather than jq.
set -euo pipefail

API="${API:-http://localhost:8000/api}"
PARAM="${1:-ph}"
PY="${PYTHON:-python3}"
export API PARAM

exec "$PY" - <<'PYEOF'
import json, os, sys, time, urllib.error, urllib.request

API   = os.environ["API"].rstrip("/")
PARAM = os.environ["PARAM"]

C_HEAD="\033[1;36m"; C_DIM="\033[2m"; C_OK="\033[1;32m"
C_WARN="\033[1;33m"; C_ERR="\033[1;31m"; C_OFF="\033[0m"

def say(t): print(f"\n{C_HEAD}{t}{C_OFF}")
def dim(t): print(f"{C_DIM}{t}{C_OFF}")
def hr():   dim("-"*62)

def call(path, method="GET", body=None, expect_ok=True):
    url = API + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method,
                                 headers={"Content-Type":"application/json"})
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return r.status, json.loads(r.read() or b"{}")
    except urllib.error.HTTPError as e:
        payload = e.read().decode(errors="ignore")
        if expect_ok:
            print(f"{C_ERR}  HTTP {e.code} on {path}: {payload[:160]}{C_OFF}")
        return e.code, payload
    except Exception as exc:
        print(f"{C_ERR}  Cannot reach {url} — is the API running? ({exc}){C_OFF}")
        sys.exit(1)

say("0 · Health")
_, h = call("/health")
print(f"  kafka={h['kafka_connected']}  models={len(h['models_loaded'])}"
      f"  kb_chunks={h['kb_chunks']}  llm={'local' if h['llm_available'] else 'template fallback'}")

say("1 · Flink operator plan (relational-plan decomposition)")
_, f = call("/flink/plan")
for o in f["operators"]:
    print(f"  {o['n']}. {o['name']:<22} {C_DIM}{o['detail']}{C_OFF}")
print(f"\n  {C_DIM}boundary -> {f['boundary']['flink']}{C_OFF}")
print(f"  {C_DIM}            {f['boundary']['llm']}{C_OFF}")

say(f"2 · Prediction for '{PARAM}'")
_, params = call("/parameters")
p = next((x for x in params if x["id"] == PARAM), None)
if p is None:
    print(f"{C_ERR}  unknown parameter '{PARAM}'. choose from: "
          f"{', '.join(x['id'] for x in params)}{C_OFF}")
    sys.exit(1)
value = round(p["alarm"][1] + 0.2, 3)
_, pred = call("/predict","POST",{"param":PARAM,"v_avg":value,"v_std":0.08,"v_delta":0.3})
print(f"  reading {value} {p['unit']}  (control {p['control'][0]}-{p['control'][1]})")
print(f"  P(breach in {pred['horizon_minutes']} min) = "
      f"{C_WARN}{pred['p_breach']*100:.1f}%{C_OFF}   zone={pred['zone'].upper()}")
print(f"  top driver: {pred['top_driver']}   model: {pred['model']}")

say("3 · Agent + RAG (semantic decomposition)")
event_id = f"evt-demo-{int(time.time())}"
_, card = call("/agent/run","POST",{"param":PARAM,"v_avg":value,"zone":"alarm",
                                    "p_breach":0.7,"event_id":event_id})
print("  sub-questions:")
for q in card["sub_questions"]:
    print(f"    {C_DIM}- {q}{C_OFF}")
hr()
for s in card["steps"]:
    cite = f"  [{s['citation']}]" if s["citation"] else ""
    print(f"  {s['order']}. {s['action']}{C_DIM}{cite}{C_OFF}")
hr()
print(f"  chunks fused: {card['retrieved_chunks']}   "
      f"generated by: {card['generated_by']}   confidence: {card['confidence']}")
flag = (C_WARN + "REQUIRES QA E-SIGN") if card["requires_esign"] else (C_OK + "AUTONOMOUS")
print(f"  policy: {flag}{C_OFF} - {card['esign_reason']}")

say("4 · Governance")
_, tok = call("/govern/token","POST",{"param":PARAM,"ttl_minutes":10})
c = tok["claims"]
print(f"  token: sub={c['sub']}  roles={c['roles']}  ttl={tok['ttl_minutes']}m")
_, dec = call(f"/govern/decide?event_id={event_id}","POST")
print(f"  PDP:   {C_WARN}{dec['decision']}{C_OFF}  obligations={dec['obligations']}")
print(f"         {C_DIM}{dec['reason']}{C_OFF}")
code, _ = call("/govern/sign","POST",
               {"event_id":event_id,"signer":"X","reason":"no"}, expect_ok=False)
status = f"{C_OK}correctly rejected{C_OFF}" if code == 400 else f"{C_ERR}UNEXPECTED{C_OFF}"
print(f"  signature with a 1-character name -> HTTP {code}  {status}")
_, sig = call("/govern/sign","POST",{"event_id":event_id,"signer":"Demo Operator",
              "role":"Performed by - Operator",
              "reason":"Approve corrective action within policy"})
s = sig["signature"]
print(f"  signed: {C_OK}{s['signer']}{C_OFF} · {s['role']} · {s['signed_at']}")

say("5 · Audit trail (last 6 entries)")
_, audit = call("/audit?limit=6")
for e in audit:
    print(f"  {e['ts'][11:19]}  {e['level'].upper():<5} {e['action']}")

print(f"\n{C_OK}Demo complete - every phase exercised end to end.{C_OFF}\n")
PYEOF
